### ISSUE TITLE
Anyone got a workaround till EE is updated, for M4S specifically?

### ISSUE THREAD

**Issue by Shiichibukai** [0ceal0t/EasyEyes#11]
Is it possible to get a somewhat working version for savage purposes? Friends are suffering hardcore from the effects and effectively we cant prog properly 

Is it possible someone could provide the paths for M4S to reduce some of the flashing on it maybe? Would be appreciate, or if someone has a workaround for it.

**Comment by Krojack** [comment]
I second this.  Something to remove the excessive screen shake for new Reaper skills and also the weird smoke effect around your character while flying.

It looks like updates started to EasyEyes but then just stopped.

**Comment by Shiichibukai** [comment]
Update just got pushed, thank you ocealot and sorry for the constant nagging.
