### ISSUE TITLE
Face disappears when using plugin

### ISSUE THREAD

**Issue by SelfAfflicted** [0ceal0t/EasyEyes#6]
When I enable EasyEyes my character's face, vanilla or sculpt, vanishes after redrawing via penumbra. This started happening when I noticed EasyEyes was not hiding the stealth ring effect from gatherer's sneak ability, upon enabling and disabling EasyEyes, chosen effects were hidden as expected but this bug, as I assume it is, with my character's face started happening. If you need any other info please let me know.

https://user-images.githubusercontent.com/13339406/223724693-78ebff74-de69-4b93-aba9-19d7da37117d.mp4

**Comment by 0ceal0t** [comment]
Fixed with latest update
